/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mvcServiceBuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TimeSheet service. Represents a row in the &quot;FOO_TimeSheet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mvcServiceBuilder.model.impl.TimeSheetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mvcServiceBuilder.model.impl.TimeSheetImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimeSheet
 * @generated
 */
@ProviderType
public interface TimeSheetModel
	extends BaseModel<TimeSheet>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a time sheet model instance should use the {@link TimeSheet} interface instead.
	 */

	/**
	 * Returns the primary key of this time sheet.
	 *
	 * @return the primary key of this time sheet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this time sheet.
	 *
	 * @param primaryKey the primary key of this time sheet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this time sheet.
	 *
	 * @return the uuid of this time sheet
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this time sheet.
	 *
	 * @param uuid the uuid of this time sheet
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the time sheet ID of this time sheet.
	 *
	 * @return the time sheet ID of this time sheet
	 */
	public long getTimeSheetId();

	/**
	 * Sets the time sheet ID of this time sheet.
	 *
	 * @param timeSheetId the time sheet ID of this time sheet
	 */
	public void setTimeSheetId(long timeSheetId);

	/**
	 * Returns the group ID of this time sheet.
	 *
	 * @return the group ID of this time sheet
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this time sheet.
	 *
	 * @param groupId the group ID of this time sheet
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this time sheet.
	 *
	 * @return the company ID of this time sheet
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this time sheet.
	 *
	 * @param companyId the company ID of this time sheet
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this time sheet.
	 *
	 * @return the user ID of this time sheet
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this time sheet.
	 *
	 * @param userId the user ID of this time sheet
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this time sheet.
	 *
	 * @return the user uuid of this time sheet
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this time sheet.
	 *
	 * @param userUuid the user uuid of this time sheet
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this time sheet.
	 *
	 * @return the user name of this time sheet
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this time sheet.
	 *
	 * @param userName the user name of this time sheet
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this time sheet.
	 *
	 * @return the create date of this time sheet
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this time sheet.
	 *
	 * @param createDate the create date of this time sheet
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this time sheet.
	 *
	 * @return the modified date of this time sheet
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this time sheet.
	 *
	 * @param modifiedDate the modified date of this time sheet
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this time sheet.
	 *
	 * @return the name of this time sheet
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this time sheet.
	 *
	 * @param name the name of this time sheet
	 */
	public void setName(String name);

	/**
	 * Returns the job name of this time sheet.
	 *
	 * @return the job name of this time sheet
	 */
	@AutoEscape
	public String getJobName();

	/**
	 * Sets the job name of this time sheet.
	 *
	 * @param jobName the job name of this time sheet
	 */
	public void setJobName(String jobName);

	/**
	 * Returns the description of this time sheet.
	 *
	 * @return the description of this time sheet
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this time sheet.
	 *
	 * @param description the description of this time sheet
	 */
	public void setDescription(String description);

	/**
	 * Returns the date of this time sheet.
	 *
	 * @return the date of this time sheet
	 */
	public Date getDate();

	/**
	 * Sets the date of this time sheet.
	 *
	 * @param date the date of this time sheet
	 */
	public void setDate(Date date);

	/**
	 * Returns the hour of this time sheet.
	 *
	 * @return the hour of this time sheet
	 */
	public int getHour();

	/**
	 * Sets the hour of this time sheet.
	 *
	 * @param hour the hour of this time sheet
	 */
	public void setHour(int hour);

	/**
	 * Returns the status of this time sheet.
	 *
	 * @return the status of this time sheet
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this time sheet.
	 *
	 * @param status the status of this time sheet
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this time sheet.
	 *
	 * @return the status by user ID of this time sheet
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this time sheet.
	 *
	 * @param statusByUserId the status by user ID of this time sheet
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this time sheet.
	 *
	 * @return the status by user uuid of this time sheet
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this time sheet.
	 *
	 * @param statusByUserUuid the status by user uuid of this time sheet
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this time sheet.
	 *
	 * @return the status by user name of this time sheet
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this time sheet.
	 *
	 * @param statusByUserName the status by user name of this time sheet
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this time sheet.
	 *
	 * @return the status date of this time sheet
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this time sheet.
	 *
	 * @param statusDate the status date of this time sheet
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this time sheet is approved.
	 *
	 * @return <code>true</code> if this time sheet is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this time sheet is denied.
	 *
	 * @return <code>true</code> if this time sheet is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this time sheet is a draft.
	 *
	 * @return <code>true</code> if this time sheet is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this time sheet is expired.
	 *
	 * @return <code>true</code> if this time sheet is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this time sheet is inactive.
	 *
	 * @return <code>true</code> if this time sheet is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this time sheet is incomplete.
	 *
	 * @return <code>true</code> if this time sheet is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this time sheet is pending.
	 *
	 * @return <code>true</code> if this time sheet is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this time sheet is scheduled.
	 *
	 * @return <code>true</code> if this time sheet is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public TimeSheet cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}