/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mvcServiceBuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.mvcServiceBuilder.model.TimeSheet;
import com.mvcServiceBuilder.model.TimeSheetModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TimeSheet service. Represents a row in the &quot;FOO_TimeSheet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TimeSheetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimeSheetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimeSheetImpl
 * @generated
 */
@JSON(strict = true)
public class TimeSheetModelImpl
	extends BaseModelImpl<TimeSheet> implements TimeSheetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a time sheet model instance should use the <code>TimeSheet</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_TimeSheet";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"timeSheetId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"jobName", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"date_", Types.TIMESTAMP},
		{"hour", Types.INTEGER}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timeSheetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hour", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_TimeSheet (uuid_ VARCHAR(75) null,timeSheetId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,jobName VARCHAR(75) null,description VARCHAR(75) null,date_ DATE null,hour INTEGER,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table FOO_TimeSheet";

	public static final String ORDER_BY_JPQL = " ORDER BY timeSheet.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_TimeSheet.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mvcServiceBuilder.service.util.ServiceProps.get(
			"lock.expiration.time.com.mvcServiceBuilder.model.TimeSheet"));

	public TimeSheetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _timeSheetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTimeSheetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _timeSheetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TimeSheet.class;
	}

	@Override
	public String getModelClassName() {
		return TimeSheet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TimeSheet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TimeSheet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimeSheet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TimeSheet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TimeSheet, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TimeSheet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TimeSheet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TimeSheet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TimeSheet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TimeSheet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TimeSheet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TimeSheet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TimeSheet, Object>>();
		Map<String, BiConsumer<TimeSheet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TimeSheet, ?>>();

		attributeGetterFunctions.put("uuid", TimeSheet::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<TimeSheet, String>)TimeSheet::setUuid);
		attributeGetterFunctions.put("timeSheetId", TimeSheet::getTimeSheetId);
		attributeSetterBiConsumers.put(
			"timeSheetId",
			(BiConsumer<TimeSheet, Long>)TimeSheet::setTimeSheetId);
		attributeGetterFunctions.put("groupId", TimeSheet::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<TimeSheet, Long>)TimeSheet::setGroupId);
		attributeGetterFunctions.put("companyId", TimeSheet::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<TimeSheet, Long>)TimeSheet::setCompanyId);
		attributeGetterFunctions.put("userId", TimeSheet::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TimeSheet, Long>)TimeSheet::setUserId);
		attributeGetterFunctions.put("userName", TimeSheet::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<TimeSheet, String>)TimeSheet::setUserName);
		attributeGetterFunctions.put("createDate", TimeSheet::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TimeSheet, Date>)TimeSheet::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TimeSheet::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TimeSheet, Date>)TimeSheet::setModifiedDate);
		attributeGetterFunctions.put("name", TimeSheet::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<TimeSheet, String>)TimeSheet::setName);
		attributeGetterFunctions.put("jobName", TimeSheet::getJobName);
		attributeSetterBiConsumers.put(
			"jobName", (BiConsumer<TimeSheet, String>)TimeSheet::setJobName);
		attributeGetterFunctions.put("description", TimeSheet::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<TimeSheet, String>)TimeSheet::setDescription);
		attributeGetterFunctions.put("date", TimeSheet::getDate);
		attributeSetterBiConsumers.put(
			"date", (BiConsumer<TimeSheet, Date>)TimeSheet::setDate);
		attributeGetterFunctions.put("hour", TimeSheet::getHour);
		attributeSetterBiConsumers.put(
			"hour", (BiConsumer<TimeSheet, Integer>)TimeSheet::setHour);
		attributeGetterFunctions.put("status", TimeSheet::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<TimeSheet, Integer>)TimeSheet::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", TimeSheet::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<TimeSheet, Long>)TimeSheet::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", TimeSheet::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<TimeSheet, String>)TimeSheet::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", TimeSheet::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<TimeSheet, Date>)TimeSheet::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTimeSheetId() {
		return _timeSheetId;
	}

	@Override
	public void setTimeSheetId(long timeSheetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timeSheetId = timeSheetId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getJobName() {
		if (_jobName == null) {
			return "";
		}
		else {
			return _jobName;
		}
	}

	@Override
	public void setJobName(String jobName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jobName = jobName;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_date = date;
	}

	@JSON
	@Override
	public int getHour() {
		return _hour;
	}

	@Override
	public void setHour(int hour) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hour = hour;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TimeSheet.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TimeSheet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TimeSheet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TimeSheet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TimeSheetImpl timeSheetImpl = new TimeSheetImpl();

		timeSheetImpl.setUuid(getUuid());
		timeSheetImpl.setTimeSheetId(getTimeSheetId());
		timeSheetImpl.setGroupId(getGroupId());
		timeSheetImpl.setCompanyId(getCompanyId());
		timeSheetImpl.setUserId(getUserId());
		timeSheetImpl.setUserName(getUserName());
		timeSheetImpl.setCreateDate(getCreateDate());
		timeSheetImpl.setModifiedDate(getModifiedDate());
		timeSheetImpl.setName(getName());
		timeSheetImpl.setJobName(getJobName());
		timeSheetImpl.setDescription(getDescription());
		timeSheetImpl.setDate(getDate());
		timeSheetImpl.setHour(getHour());
		timeSheetImpl.setStatus(getStatus());
		timeSheetImpl.setStatusByUserId(getStatusByUserId());
		timeSheetImpl.setStatusByUserName(getStatusByUserName());
		timeSheetImpl.setStatusDate(getStatusDate());

		timeSheetImpl.resetOriginalValues();

		return timeSheetImpl;
	}

	@Override
	public TimeSheet cloneWithOriginalValues() {
		TimeSheetImpl timeSheetImpl = new TimeSheetImpl();

		timeSheetImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		timeSheetImpl.setTimeSheetId(
			this.<Long>getColumnOriginalValue("timeSheetId"));
		timeSheetImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		timeSheetImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		timeSheetImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		timeSheetImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		timeSheetImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		timeSheetImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		timeSheetImpl.setName(this.<String>getColumnOriginalValue("name"));
		timeSheetImpl.setJobName(
			this.<String>getColumnOriginalValue("jobName"));
		timeSheetImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		timeSheetImpl.setDate(this.<Date>getColumnOriginalValue("date_"));
		timeSheetImpl.setHour(this.<Integer>getColumnOriginalValue("hour"));
		timeSheetImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		timeSheetImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		timeSheetImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		timeSheetImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return timeSheetImpl;
	}

	@Override
	public int compareTo(TimeSheet timeSheet) {
		int value = 0;

		value = getName().compareTo(timeSheet.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TimeSheet)) {
			return false;
		}

		TimeSheet timeSheet = (TimeSheet)object;

		long primaryKey = timeSheet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TimeSheet> toCacheModel() {
		TimeSheetCacheModel timeSheetCacheModel = new TimeSheetCacheModel();

		timeSheetCacheModel.uuid = getUuid();

		String uuid = timeSheetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			timeSheetCacheModel.uuid = null;
		}

		timeSheetCacheModel.timeSheetId = getTimeSheetId();

		timeSheetCacheModel.groupId = getGroupId();

		timeSheetCacheModel.companyId = getCompanyId();

		timeSheetCacheModel.userId = getUserId();

		timeSheetCacheModel.userName = getUserName();

		String userName = timeSheetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			timeSheetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			timeSheetCacheModel.createDate = createDate.getTime();
		}
		else {
			timeSheetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			timeSheetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			timeSheetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		timeSheetCacheModel.name = getName();

		String name = timeSheetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			timeSheetCacheModel.name = null;
		}

		timeSheetCacheModel.jobName = getJobName();

		String jobName = timeSheetCacheModel.jobName;

		if ((jobName != null) && (jobName.length() == 0)) {
			timeSheetCacheModel.jobName = null;
		}

		timeSheetCacheModel.description = getDescription();

		String description = timeSheetCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			timeSheetCacheModel.description = null;
		}

		Date date = getDate();

		if (date != null) {
			timeSheetCacheModel.date = date.getTime();
		}
		else {
			timeSheetCacheModel.date = Long.MIN_VALUE;
		}

		timeSheetCacheModel.hour = getHour();

		timeSheetCacheModel.status = getStatus();

		timeSheetCacheModel.statusByUserId = getStatusByUserId();

		timeSheetCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = timeSheetCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			timeSheetCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			timeSheetCacheModel.statusDate = statusDate.getTime();
		}
		else {
			timeSheetCacheModel.statusDate = Long.MIN_VALUE;
		}

		return timeSheetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TimeSheet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TimeSheet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimeSheet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TimeSheet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TimeSheet>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TimeSheet.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _timeSheetId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _jobName;
	private String _description;
	private Date _date;
	private int _hour;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TimeSheet, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TimeSheet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("timeSheetId", _timeSheetId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("jobName", _jobName);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("date_", _date);
		_columnOriginalValues.put("hour", _hour);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("date_", "date");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("timeSheetId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("jobName", 512L);

		columnBitmasks.put("description", 1024L);

		columnBitmasks.put("date_", 2048L);

		columnBitmasks.put("hour", 4096L);

		columnBitmasks.put("status", 8192L);

		columnBitmasks.put("statusByUserId", 16384L);

		columnBitmasks.put("statusByUserName", 32768L);

		columnBitmasks.put("statusDate", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TimeSheet _escapedModel;

}